[package]
name = "grid"
version = "0.1.0"
authors = ["Daniel-del-Castillo <alu0101225548@alu.edu.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
crossterm = "0.18.0"
fxhash = "0.2.1"